/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'massimo' at '29/10/17 21:29' with Gradle 3.2.1
 *
 * @author massimo, @date 29/10/17 21:29
 */
public class ModuleBMain {

    public static String foo() {
        return "module b main";
    }
}
