/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'massimo' at '29/10/17 21:29' with Gradle 3.2.1
 *
 * @author massimo, @date 29/10/17 21:29
 */
public class ModuleAMain {

    public static String foo() {
        ModuleBMain.foo();
        ModuleBTools.foo();
        return "module b main";
    }

}
